import { useEffect } from "react";
import { Link, useParams } from "react-router-dom";
import ModernInnerHero from "../components/ModernInnerHero";

const img = (path) => `${import.meta.env.BASE_URL}${path.replace(/^\/+/, "")}`;

const DESTINATIONS = {
  uk: {
    name: "United Kingdom (UK)", flag: "🇬🇧", eyebrow: "STUDY IN THE UK", image: "/images/hero-uk.png",
    title: "Your UK story can start here, and it won't cost you a fee.",
    intro: "From your first campus shortlist to your first cup of tea in a new city, we guide you personally through every step of studying in the United Kingdom.",
    highlights: [
      ["Shorter degrees", "Most bachelor's courses run three years and many master's courses one year."],
      ["Globally recognised", "UK qualifications are respected by employers and universities around the world."],
      ["Room to work", "Eligible students may have limited work rights depending on their course and visa conditions."],
      ["Life after study", "Eligible graduates may have post-study options subject to the rules in force when they apply."]
    ],
    promise: "Course and university shortlisting, portfolio building, SOP writing, application submission, visa assistance, accommodation help, and alumni networking. You pay the university and government fees that apply to you. You never pay us for our counselling service.",
    costs: ["Tuition fees vary by university and course", "Student visa and health-related charges may apply", "Living costs vary by city and lifestyle", "Always confirm the latest official figures before applying"],
    steps: ["A real conversation", "A shortlist you understand", "Your profile and SOP", "Applications and offers", "Visa and funds", "Landing softly"],
    faqs: ["Can I work while I study?", "Can I stay after my degree?", "Can my family come with me?", "Is it really free to work with you?"]
  },
  usa: { name: "United States of America (USA)", flag: "🇺🇸", eyebrow: "STUDY IN THE USA", image: "/images/hero-usa-modern.png", title: "Build your next chapter in the United States.", intro: "Explore universities, flexible degree structures, campus life and career-focused programs with guidance from shortlist to application.", highlights: [["Wide university choice", "Choose from research universities, liberal arts colleges and specialist institutions."],["Flexible study", "Many programs offer room to explore subjects before committing to a final academic path."],["STEM opportunities", "The USA offers a large range of technology, engineering and science programs."],["Campus experience", "Student clubs, research, internships and campus communities are part of the experience."]], promise: "We help with profile evaluation, university shortlisting, application planning, SOP support, scholarship research, visa documentation and pre-departure guidance.", costs: ["Tuition varies widely by institution and program", "Housing and living costs depend on the city", "Application and visa charges may apply", "Confirm current figures with the university and official authorities"], steps: ["Understand your goals", "Build a balanced shortlist", "Prepare applications", "Compare offers", "Prepare your visa documents", "Get ready to travel"], faqs: ["How do I choose between universities?", "Can I apply for scholarships?", "What tests may be required?", "How early should I start?"] },
  canada: { name: "Canada", flag: "🇨🇦", eyebrow: "STUDY IN CANADA", image: "/images/hero-canada.png", title: "Find a Canadian campus that fits your future.", intro: "Plan your Canadian study journey with practical guidance on programs, universities, applications and pre-departure preparation.", highlights: [["Strong academic options", "Choose from universities, colleges and specialised institutions across Canada."],["Career-focused programs", "Many programs combine academic learning with practical and industry-oriented study."],["Multicultural environment", "Canadian campuses welcome students from many countries and backgrounds."],["Student support", "We help you understand applications, documents and next steps before you travel."]], promise: "From course selection to application tracking and visa-document preparation, we keep the process organised and transparent.", costs: ["Tuition differs by institution and program", "Living costs vary significantly by province and city", "Application and government charges may apply", "Check the latest official requirements before applying"], steps: ["Profile discussion", "Program and college/university shortlist", "Application preparation", "Offer review", "Visa preparation", "Pre-departure support"], faqs: ["University or college—which is right for me?", "What documents are needed?", "Are scholarships available?", "When should I apply?"] },
  australia: { name: "Australia", flag: "🇦🇺", eyebrow: "STUDY IN AUSTRALIA", image: "/images/hero-australia.png", title: "Make Australia part of your study story.", intro: "Explore universities and practical study options across Australia's major student cities with guidance throughout your application journey.", highlights: [["Globally recognised education", "Australian institutions offer a broad range of undergraduate and postgraduate programs."],["Practical learning", "Many courses connect academic study with projects, placements or industry exposure."],["Student cities", "Choose from diverse study environments including Sydney, Melbourne, Brisbane and more."],["International community", "Meet students from around the world while building your academic network."]], promise: "We support course selection, university shortlisting, applications, documentation, visa preparation and pre-departure planning.", costs: ["Tuition varies by institution and course", "Living costs depend on location and lifestyle", "Visa and health-related charges may apply", "Confirm current figures from official sources"], steps: ["Profile assessment", "Course and university shortlist", "Application submission", "Offer and financial planning", "Visa preparation", "Pre-departure support"], faqs: ["Which Australian city should I choose?", "What courses are popular?", "Can I get scholarships?", "What should I prepare before applying?"] },
  "new-zealand": { name: "New Zealand", flag: "🇳🇿", eyebrow: "STUDY IN NEW ZEALAND", image: "/images/hero-new-zealand-modern.png", title: "Study in New Zealand with a clear plan.", intro: "Discover universities and institutes with a focus on practical education, student support and a balanced study experience.", highlights: [["Quality education", "New Zealand offers universities and institutes across many academic fields."],["Practical pathways", "Many programs emphasise applied learning and career preparation."],["Welcoming campuses", "International students can experience a diverse and supportive study environment."],["Balanced lifestyle", "Study alongside a lifestyle that offers access to cities, nature and outdoor activities."]], promise: "We help you compare programs, prepare applications and understand the documentation needed for your study journey.", costs: ["Fees depend on program and institution", "Living costs depend on city and accommodation", "Government and visa charges may apply", "Verify current requirements before submission"], steps: ["Discuss your goals", "Choose programs", "Prepare documents", "Apply and track", "Prepare visa documents", "Plan your arrival"], faqs: ["What can I study in New Zealand?", "How do I choose an institution?", "What documents are required?", "When should I begin?"] },
  germany: { name: "Germany", flag: "🇩🇪", eyebrow: "STUDY IN GERMANY", image: "/images/hero-germany.png", title: "Explore study opportunities in Germany.", intro: "Plan your German study journey around the right program, institution, language requirements and application timeline.", highlights: [["Research and technical strengths", "Germany is known for a wide range of engineering, technology, science and business programs."],["Public and private institutions", "Compare different institution types and program structures."],["International programs", "A growing number of programs are available with English-taught options."],["Career preparation", "Build a study plan aligned with your academic and professional goals."]], promise: "We help you shortlist programs, understand requirements, prepare documents and organise your application journey.", costs: ["Costs depend on institution, program and city", "Living expenses vary by location", "Visa and residence requirements may apply", "Always verify current rules with official sources"], steps: ["Academic profile review", "Program shortlist", "Language and document check", "Application", "Visa preparation", "Pre-departure planning"], faqs: ["Do I need German?", "Which programs are taught in English?", "How do I compare institutions?", "What documents are required?"] },
  ireland: { name: "Ireland", flag: "🇮🇪", eyebrow: "STUDY IN IRELAND", image: "/images/hero-ireland.png", title: "Take your next academic step in Ireland.", intro: "Explore Irish universities and institutes across business, technology, science, healthcare and other popular fields.", highlights: [["Strong academic ecosystem", "Ireland offers recognised universities and institutes across many disciplines."],["Technology and business", "The country has a strong presence of technology and international businesses."],["English-speaking environment", "Programs and daily life offer an accessible English-speaking study environment."],["International student community", "Meet students from different countries and build global connections."]], promise: "We support course selection, institution shortlisting, applications, document preparation and pre-departure guidance.", costs: ["Fees vary by course and institution", "Accommodation costs depend on location", "Visa and government charges may apply", "Confirm current figures before applying"], steps: ["Profile assessment", "Course shortlist", "Application preparation", "Offer review", "Visa documents", "Arrival planning"], faqs: ["Which courses are popular?", "How do I choose an institution?", "Are scholarships available?", "What is the application timeline?"] },
  singapore: { name: "Singapore", flag: "🇸🇬", eyebrow: "STUDY IN SINGAPORE", image: "/images/hero-singapore-modern.png", title: "Build a global career from Singapore.", intro: "Explore universities and institutes in a highly international study environment with strong links to business and technology.", highlights: [["Global education hub", "Singapore hosts universities and international institutions serving students from around the world."],["Technology and business", "Programs across technology, finance, management and related fields are popular."],["Connected location", "Its location provides access to a wider Asian business and cultural environment."],["Modern student life", "Students can experience a compact, connected and multicultural city."]], promise: "We help compare programs, understand entry requirements, prepare applications and organise the next steps.", costs: ["Tuition varies by institution and program", "Accommodation and living costs vary", "Visa/student-pass requirements may apply", "Check current official figures before applying"], steps: ["Discuss goals", "Shortlist programs", "Prepare application", "Review offer", "Prepare student-pass documents", "Plan arrival"], faqs: ["Which institutions should I consider?", "What programs are popular?", "What are the entry requirements?", "How should I budget?"] },
  france: { name: "France", flag: "🇫🇷", eyebrow: "STUDY IN FRANCE", image: "/images/hero-france-modern.png", title: "Discover your study options in France.", intro: "Explore French universities and institutions across business, design, hospitality, engineering, arts and more.", highlights: [["Broad academic choice", "France offers programs across traditional and professional disciplines."],["Business and design", "Management, luxury, fashion, hospitality and design are popular study areas."],["International environment", "Many institutions welcome students from around the world."],["European exposure", "Study in a country with access to a wider European academic and cultural environment."]], promise: "We guide you through program selection, institution shortlisting, applications and pre-departure preparation.", costs: ["Fees depend on institution and program", "Living costs vary by city", "Visa and administrative charges may apply", "Verify current requirements before applying"], steps: ["Profile discussion", "Program shortlist", "Application documents", "Submission and tracking", "Visa preparation", "Arrival planning"], faqs: ["Do I need French?", "Which programs are taught in English?", "How do I compare institutions?", "What should I budget?"] },
  italy: { name: "Italy", flag: "🇮🇹", eyebrow: "STUDY IN ITALY", image: "/images/hero-italy.png", title: "Turn your academic goals into an Italian study plan.", intro: "Explore Italian universities and specialist institutions across engineering, architecture, design, business, arts and more.", highlights: [["Historic academic institutions", "Italy offers a wide selection of universities and specialist schools."],["Design and architecture", "Design, architecture, fashion and creative disciplines are well represented."],["Engineering and business", "Students can choose from programs across technical and management fields."],["Cultural experience", "Study alongside an international community in diverse Italian cities."]], promise: "We help you compare programs, organise documents, submit applications and prepare for your move.", costs: ["Fees vary by institution and program", "Living expenses differ by city", "Visa and administrative charges may apply", "Confirm current figures from official sources"], steps: ["Understand your goals", "Shortlist programs", "Prepare documents", "Submit applications", "Prepare visa", "Plan arrival"], faqs: ["Which programs are popular?", "Do I need Italian?", "Are English-taught programs available?", "What is the application timeline?"] },
  europe: { name: "Europe (More Countries)", flag: "🇪🇺", eyebrow: "STUDY IN EUROPE", image: "/images/hero-europe.png", title: "Compare more European study destinations.", intro: "If the UK, Germany, France or Italy is not the right fit, we can help you explore additional European study destinations based on your goals.", highlights: [["More choices", "Compare institutions and programs across a wider range of European countries."],["Different budgets", "Explore options with different tuition and living-cost profiles."],["Multiple disciplines", "From business and engineering to healthcare, design and technology."],["Personal guidance", "We help you narrow the choices instead of sending you a generic list."]], promise: "Tell us your course, budget and preferred region and we can help build a practical shortlist.", costs: ["Tuition and living costs vary by country", "Visa requirements differ by destination", "Language requirements differ by program", "Always verify current requirements before applying"], steps: ["Share your profile", "Compare countries", "Shortlist programs", "Prepare applications", "Complete visa steps", "Prepare for departure"], faqs: ["Which European country fits my budget?", "Can I study in English?", "How do I compare countries?", "What documents will I need?"] }
};

export default function DestinationDetail({ slug: fixedSlug }) {
  const { slug: routeSlug } = useParams();
  const slug = fixedSlug || routeSlug;
  const data = DESTINATIONS[slug] || DESTINATIONS.uk;

  useEffect(() => {
    document.title = `Study in ${data.name} | Go2Abroad`;
    window.scrollTo(0, 0);
  }, [data.name]);

  return (
    <main className="g2-detail-page">
      <ModernInnerHero
        eyebrow={`${data.flag} ${data.eyebrow}`}
        title={data.title}
        intro={data.intro}
        image={data.image}
        imageAlt={`Study in ${data.name}`}
        badge={`Study in ${data.name}`}
        primaryLabel="Talk to a counsellor"
        secondaryLabel="View destination details"
        secondaryTo="#why"
        meta={["Free counselling", "University matching", "Visa guidance"]}
        themeKey={slug || "brand"}
      />

      <section id="why" className="g2-detail-section"><div className="container"><div className="g2-detail-heading"><span>WHY STUDENTS CONSIDER IT</span><h2>Plan your study journey with clarity</h2><p>Every destination has different institutions, course structures, entry requirements and costs. We help you compare the details that matter to you.</p></div><div className="g2-detail-grid">{data.highlights.map(([title, text], i) => <article className="g2-detail-card" key={title}><b>0{i + 1}</b><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className="g2-detail-section g2-detail-soft"><div className="container"><div className="g2-detail-promise"><span>OUR SUPPORT</span><h2>Guidance from shortlist to departure</h2><p>{data.promise}</p></div></div></section>

      <section className="g2-detail-section"><div className="container"><div className="g2-detail-two"><div><span className="g2-detail-kicker">COST PLANNING</span><h2>Know what to plan for</h2><p>Costs depend on your course, institution and location. We help you build a realistic plan before you submit an application.</p></div><ul className="g2-detail-list">{data.costs.map(item => <li key={item}><i className="fa-solid fa-check" />{item}</li>)}</ul></div></div></section>

      <section className="g2-detail-section g2-detail-soft"><div className="container"><div className="g2-detail-heading"><span>OUR PROCESS</span><h2>From dream to departure</h2></div><ol className="g2-detail-steps">{data.steps.map((step, i) => <li key={step}><b>{String(i + 1).padStart(2, "0")}</b><div><h3>{step}</h3><p>We keep this stage organised and explain the next action clearly.</p></div></li>)}</ol></div></section>

      <section className="g2-detail-section"><div className="container"><div className="g2-detail-heading"><span>FREQUENT QUESTIONS</span><h2>Questions families ask</h2></div><div className="g2-faq-grid">{data.faqs.map(q => <details key={q}><summary>{q}</summary><p>We will review your profile, course, destination and current requirements with you before you apply.</p></details>)}</div></div></section>

      <section className="g2-detail-cta"><div className="container"><h2>Ready to explore {data.name}?</h2><p>Tell us your course, budget or current academic profile and we will help you plan the next step.</p><Link to="/contact" className="sis-btn-default">Book Free Consultation <i className="fa-solid fa-arrow-right-long" /></Link></div></section>
    </main>
  );
}

export { DESTINATIONS };
