import { useEffect, useState } from "react";
import { Link } from "react-router-dom";

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:4000";
const imageUrl = (value) => value && (/^(https?:|data:|blob:)/.test(value) ? value : `${import.meta.env.BASE_URL}${value.replace(/^\/+/, "")}`);

export default function University() {
  const [universities, setUniversities] = useState([]);
  const [state, setState] = useState("loading");
  useEffect(() => { fetch(`${API_URL}/public/universities`).then((r) => r.ok ? r.json() : Promise.reject(new Error())).then((data) => { setUniversities(Array.isArray(data) ? data : []); setState("ready"); }).catch(() => setState("error")); }, []);
  return <section className="sis-university-section position-relative bg-white section sis-brand-gradient-soft"><div className="container"><div className="row align-items-end"><div className="col-lg-6"><div className="sisf-sis-section-title sis-section-title"><span className="sisf-m-subtitle sis-comman-bg">TOP UNIVERSITIES</span><h2 className="sisf-m-title">Study at <span className="sisf-e-colored">globally recognised</span> institutions.</h2></div></div><div className="col-lg-6"><p>A shortlist of universities that welcome Indian students, with strong course options and proven outcomes.</p><Link className="sis-btn-default" to="/usa#top-universities">View All Universities <i className="fa-solid fa-arrow-right-long"></i></Link></div></div>{state === "loading" && <p>Loading universities…</p>}{state === "error" && <p>University information is temporarily unavailable. Please contact us for guidance.</p>}{state === "ready" && !universities.length && <p>No published universities are available yet.</p>}<div className="row">{universities.map((university) => <div className="col-lg-4 col-md-6 mb-4" key={university.id}><a href={university.website || `/usa#${university.slug}`} target={university.website ? "_blank" : undefined} rel={university.website ? "noopener noreferrer" : undefined} className="sis-country-card d-block"><div className="sis-country-card-top">{university.logoUrl && <img src={imageUrl(university.logoUrl)} alt="" className="sis-country-flag" />}<div><h3>{university.name}</h3><span className="sis-country-tag">{[university.city, university.country].filter(Boolean).join(", ")}</span></div></div><div className="sis-country-card-body"><p>{university.description || "Explore courses, admissions, and study opportunities."}</p><span className="sis-country-card-link">View Details <i className="fa-solid fa-arrow-right-long"></i></span></div></a></div>)}</div></div></section>;
}
